#!/bin/bash
xprop -spy -root _XKB_RULES_NAMES | while read -r line; do
   variant=$(echo $line | cut -d',' -f4 | tr -d '"') 
   if [[ "$variant" == " cdhpt" ]]; then
     echo ""
   else
     echo ""
   fi
done
