#!/bin/bash

if [ -z "$1" ]; then
  theme=$(defaults read -g AppleInterfaceStyle | tr '[:upper:]' '[:lower:]')
else
  theme="$1"
fi

PATH="/opt/homebrew/bin/:$PATH"

if [ "$theme" == "dark" ]; then
  gsed -i 's/kanagawa_light.conf/kanagawa.conf/g' "$HOME/.config/kitty/kitty.conf"
  gsed -i 's/tokyonight_day/tokyonight_storm/g' "$HOME/.config/kitty/kitty.conf"
  gsed -i 's/Light/Origin/g' "$HOME/.config/bat/config"
  gsed -i 's/flat-remix-light/tokyo-storm/g' "$HOME/.config/btop/btop.conf"
  gsed -i "\$s/.*/include dark-256.theme/" "$HOME/.config/task/taskrc"
  echo "dark" > "$HOME/.theme"
else
  theme="light"
  gsed -i 's/kanagawa.conf/kanagawa_light.conf/g' "$HOME/.config/kitty/kitty.conf"
  gsed -i 's/tokyonight_storm/tokyonight_day/g' "$HOME/.config/kitty/kitty.conf"
  gsed -i 's/Origin/Light/g' "$HOME/.config/bat/config"
  gsed -i 's/tokyo-storm/flat-remix-light/g' "$HOME/.config/btop/btop.conf"
  gsed -i "\$s/.*/include light-256.theme/" "$HOME/.config/task/taskrc"
  echo "light" > "$HOME/.theme"
fi

# pgrep -f kitty | xargs kill -SIGUSR1
kill -SIGUSR1 $(pgrep -f kitty)
# tmux source-file "$HOME/.config/tmux/$theme.conf"


# This uses the neovim-remote python package to control other neovim instances.
# see: https://github.com/mhinz/neovim-remote
# Further, it is assumed that toggling the background in neovim is enough.
# Anything else should be handled by the set color scheme.

for server in $(nvr --serverlist); do
    nvr --servername "$server" -cc "set background=$theme"
done
